name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy_id: "${{ steps.deploy.outputs.deploy_id }}"
      deploy_url: "${{ steps.deploy.outputs.deploy_url }}"
      logs: "${{ steps.deploy.outputs.logs }}"
    environment:
      name: default
      url: "${{ steps.deploy.outputs.deploy_url }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install -g netlify-cli
      - run: npm ci
      - run: npm run build
      - run: find dist/ -type f
      - id: deploy
        name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: "${{ secrets.NETLIFY_AUTH_TOKEN }}"
          NETLIFY_SITE_ID: "${{ secrets.NETLIFY_SITE_ID }}"
        run: |
          set -eux
          netlify deploy --site=$NETLIFY_SITE_ID --dir=dist --prod --json | tee deploy.json
          cat deploy.json
          echo "::set-output name=deploy_id::$(jq -r '.deploy_id' deploy.json)"
          echo "::set-output name=deploy_url::$(jq -r '.deploy_url' deploy.json)"
          echo "::set-output name=logs::$(jq -r '.logs' deploy.json)"
