name: Build and Deploy

on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/workflows/docker-image.yml'
      - '.gitignore'
      - '*.md'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/somosaseb/somosaseb-website/base:latest
    environment:
      name: default
      url: "${{ steps.outputs.outputs.deploy_url }}"
    defaults:
      run:
        working-directory: /app
    outputs:
      deploy_id: ${{ steps.outputs.outputs.deploy_id }}
      deploy_url: ${{ steps.outputs.outputs.deploy_url }}
      logs_url: ${{ steps.outputs.outputs.logs_url }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - run: cp -ar $GITHUB_WORKSPACE/* .
      - run: npm run build
      - run: find dist/ -type f
      -
        id: deploy
        name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: "${{ secrets.NETLIFY_AUTH_TOKEN }}"
          NETLIFY_SITE_ID: "${{ secrets.NETLIFY_SITE_ID }}"
        run: netlify deploy --site=$NETLIFY_SITE_ID --dir=dist --prod --json | tee deploy.json
      -
        name: outputs
        run: |
          set -eu
          echo "::set-output name=deploy_id::$(jq -r '.deploy_id' deploy.json)"
          echo "::set-output name=deploy_url::$(jq -r '.deploy_url' deploy.json)"
          echo "::set-output name=logs_url::$(jq -r '.logs' deploy.json)"
