name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy_id: "${{ steps.build.outputs.deploy_id }}"
      deploy_url: "${{ steps.build.outputs.deploy_url }}"
      logs: "${{ steps.build.outputs.logs }}"
    environment:
      name: default
      url: https://somosaseb-website.netlify.app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install -g netlify-cli
      - run: npm ci
      - run: npm run build
      - run: find dist/ -type f
      - id: random-number-generator
        run: |
          OUT="$(netlify deploy --site=$NETLIFY_SITE_ID --dir=dist --prod)";
          echo "::set-output name=deploy_id::$(echo $OUT | jq -r '.deploy_id')";
          echo "::set-output name=deploy_url::$(echo $OUT | jq -r '.deploy_url')";
          echo "::set-output name=logs::$(echo $OUT | jq -r '.logs')";
