name: Build base docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          target: frontend-deps
          tags: ghcr.io/somosaseb/somosaseb-website/base:latest
          cache-from: type=registry,ref=ghcr.io/somosaseb/somosaseb-website/base:latest
          cache-to: type=inline
