name: Release to Production

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      -
        name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: staging.yml
          workflow_conclusion: success
          branch: master
          name: website
          path: /app/dist/
      -
        run: find . -type f
