name: Release to Production

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      -
        uses: actions/download-artifact@master
        with:
          name: website
          path: /app/dist/
      -
        run: find . -type f
